project:
  type: book
  output-dir: docs
  resources:
    - img/**

book:
  title: "Introdução à Estatística para Ciência de Dados com R"
  author: "Jorge Ubirajara Pedreira Junior"
  language: pt
  page-navigation: true
  search: true
  chapters:
    - index.qmd

    - part: "PARTE 1: ASPECTOS INTRODUTÓRIOS"
      chapters:
        - 1introducao-ao-r.qmd
        - 2planejamento-de-pesquisas.qmd

    - part: "PARTE 2: ANÁLISE EXPLORATÓRIA DE DADOS"
      chapters:
        - 3estatistica-descritiva.qmd
        - 4manipulacao-de-dados-tabulares.qmd
        - 5visualizacao-de-dados-tabulares.qmd

    - part: "PARTE 3: INTRODUÇÃO À TEORIA DA PROBABILIDADE"
      chapters:
        - 6revisao-de-teoria-dos-conjuntos.qmd
        - 7experimento-espaco-eventos.qmd
        - 8regras-multiplicacao-adicao.qmd
        - 9teorema-de-bayes.qmd
        - 10variaveis-aleatorias.qmd
        - 11lgn-e-tlc.qmd

    - part: "PARTE 4: DISTRIBUIÇÕES DE PROBABILIDADE"
      chapters:
        - 12distribuicoes-discretas.qmd
        - 13distribuicoes-continuas.qmd

    - part: "PARTE 5: INFERÊNCIA ESTATÍSTICA"
      chapters:
        - 14estimacao-de-parametros.qmd
        - 15introducao-testes-de-hipoteses.qmd
        - 16testes-t-student.qmd
        - 17testes-nao-parametricos.qmd

    - part: "PARTE 6: ESTIMANDO RELAÇÕES ENTRE VARIÁVEIS"
      chapters:
        - 18associacao-e-correlacao.qmd
        - 19regressao-linear-simples.qmd
        - 20inferencia-em-regressao.qmd
        - 21regressao-linear-multipla.qmd

    - summary.qmd
    - references.qmd

format:
  html:
    theme: default
    number-sections: true
    toc: true
    toc-depth: 3

bibliography: references.bib
crossref:
  fig-title: "Figura"
  tbl-title: "Tabela"
  eq-title: "Equação"

# (opcional) builds mais rápidos em capítulos não alterados
execute:
  freeze: auto
